#!/bin/bash

set -e

echo "Downloading Kali Linux Repository keyring archive..."
wget https://http.kali.org/pool/main/k/kali-archive-keyring/kali-archive-keyring_2025.1_all.deb

echo "Installing Kali Linux Repository keyring..."
dpkg -i ./kali-archive-keyring_2025.1_all.deb

exit 0
